CREATE TABLE ALMACENES(NIF_ESTANCO varchar(6) not null, MARCA varchar(25), FILTRO char(1), COLOR char(1), CLASE varchar(20), MENTOL char(1), UNIDADES int);
CREATE TABLE CIGARRILLOS(MARCA varchar(15) not null, FILTRO char(1), COLOR char(1), CLASE varchar(15), MENTOL char(1), NICOTINA FLOAT, ALQUITRAN int, PRECIO_COSTO int, PRECIO_VENTA int);
CREATE TABLE COMPRAS(NIF_ESTANCO varchar(6) not null, MARCA varchar(25) not null, FILTRO char(1), COLOR char(1), CLASE varchar(15), MENTOL char(1), FECHA_COMPRA date, C_COMPRADA int, PRECIO_COMPRA int);
CREATE TABLE ESTANCOS(NIF_ESTANCO varchar(6) not null, EXPENDEDURIA int, CP_ESTANCO int, NOMBRE_ESTANCO varchar(25), DIRECCION_ESTANCO varchar(25), LOCALIDAD_ESTANCO varchar(25), PROVINCIA_ESTANCO varchar(25));
CREATE TABLE FABRICANTES(NOMBRE_FABRICANTE varchar(35) not null, PAIS varchar (25));
CREATE TABLE MANUFACTURA(MARCA varchar(25) not null, NOMBRE_FABRICANTE varchar(35), CARTON int, EMBALAJE int);
CREATE TABLE VENTAS(NIF_ESTANCO varchar(6) not null, MARCA varchar(25) not null, FILTRO char(1), COLOR char(1), CLASE varchar(15), MENTOL char(1), FECHA_VENTA date, C_VENDIDA int, PRECIO_VENTA int);